# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b976d2851acf10fc9fa4b196b847c8e8f8479e2df2b4c848549825fa24eab9ef1e264bc2b9d510b10796f8f66327acc9740409d476dd32aad08bf3e259875e25

test:
  secret_key_base: 0c6828b9a604685e0c071a563af4f3890af37d9be1f9edc15bec1114ee05ab6a055a7468abbbed4730bad5a08aff3bcda6f0edb724c6f57672699dae7237375a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
